version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./build/nginx:/etc/nginx/conf.d
      - ./build/dist:/var/www/dist
      - ./build/certbot/conf:/etc/letsencrypt
      - ./build/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./build/certbot/conf:/etc/letsencrypt
      - ./build/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
